### ISSUE TITLE
Display of meme images 

### ISSUE THREAD

**Issue by imaarov** [imaarov/meme.js#8]
the current quality of the images that are displayed in the terminal is not good 
if you have any ideas for displaying images in other ways or enhancing the quality of this implementation you can explain them here

**Comment by 1p22geo** [comment]
Can we (by default) display the images using Firefox or another app?
Does it have to display in terminal, or can it be just a CLI for displaying memes *somewhere*?

How about the app **tries** to open the meme using `xdg-open`, or just using your default program for JPG files, and if that fails, use `terminal-image`.

**Comment by 1p22geo** [comment]
We can also use [`atanunq/viu`](https://github.com/atanunq/viu) but it only works with some terminals.

**Comment by imaarov** [comment]
> Can we (by default) display the images using Firefox or another app? Does it have to display in terminal, or can it be just a CLI for displaying memes _somewhere_?
> 
> How about the app **tries** to open the meme using `xdg-open`, or just using your default program for JPG files, and if that fails, use `terminal-image`.

Hi thank you for your contribution, the main functionality until now in meme.js is that show the memes into the terminal (of course it is still in the beginning phase, and lots of  other basic features are needed for that)
your idea that it should cover another app to show the image is very good, **and I will add this feature for meme.js surely**
but the terminal option for viewing should be in higher priority.

**Comment by imaarov** [comment]
> We can also use [`atanunq/viu`](https://github.com/atanunq/viu) but it only works with some terminals.

Thanks for your recommendation,
I will look it out but if I recall this depends on some specific terminal and some environment (I think it's for iterm only)

**Comment by 1p22geo** [comment]
Most terminals don't support image viewing. And `icat` or the `terminal-image` library are displaying it in the resolution the terminal allows for - one pixel per character.

Most people have a desktop environment, and opening an image viewer in an unfocused window (and closing it after the user presses `enter` or `return`, before opening another one) would be enough for most, in my opinion.

That being said, we can definitely write a NVIM or Emacs extension for that.

**Comment by imaarov** [comment]
Yes! As I said before I will add the image viewer option to show the image and the functionality that you provide is great for that and I appreciate it,
I can't find the perfect package for that, maybe there isn't, or is not possible to  make it better than `icat` or `terminal-image`
so I move on to the other features (as you say showing in image viewer apps and others...) and this issue will be closed soon.
but you can explain more about the nvim extension if you don't mind

**Comment by 1p22geo** [comment]
As for the nvim extension, I'm not really proficient in those, but that's usually Lua, not JS. I use nvim myself, and it propably has some kind of support for that.

**Comment by 1p22geo** [comment]
There's [`image.nvim`](https://github.com/3rd/image.nvim). It uses `ImageMagick`, so it might work cross-platform.

**Comment by imaarov** [comment]
Thank you for sharing it, I have to check these extensions,
but the main thing will be adding the image viewer feature with Firefox as you said, or any other apps. thank you for your recommendation.

**Comment by imaarov** [comment]
I'm using kitty icat to show in kitty terminal for now the display of images is kind of solved (in kitty terminal). now we have to find out what we should do with other terminals
